### ISSUE TITLE
Create CardLink component for Home-Page

### ISSUE THREAD

**Issue by Contrevien** [A2Z-hq/a2z-frontend#13]
If you all remember from the webpage we created earlier, it consisted of cards of different colors as a link to different sections.

**Goal:** The task is to build a reusable card component with the same CSS features as previously. It should accept a Link, a Title and a Color as props.

**Comment by Aditya-Kolla** [comment]
Lemme try.

**Comment by Contrevien** [comment]
@Aditya-Kolla Are you working on this? How is the progress?

**Comment by Aditya-Kolla** [comment]
> @Aditya-Kolla Are you working on this? How is the progress?

Sorry had an exam today. Gonna start work on it now.

**Comment by Contrevien** [comment]
@Aditya-Kolla No problem, let me know if you face any difficulty and I'll try to get it resolved.
