### ISSUE TITLE
Create the heading of the Home-page

### ISSUE THREAD

**Issue by Contrevien** [A2Z-hq/a2z-frontend#14]
As in our previous master branch, the website had a header saying "Explore the ultimate collection" and sub head saying "What do you want to do today? Learn something new? Attend a meetup"

**Goal:** Add the header and sub header in a responsive manner to the Home-page component.

**Comment by miteshree** [comment]
I have created a pull request on this. Please review it and give comments.

**Comment by Contrevien** [comment]
This issue is concluded.
