### ISSUE TITLE
Make the webpages responsive

### ISSUE THREAD

**Issue by Contrevien** [A2Z-hq/a2z-frontend#3]

**Comment by Contrevien** [comment]
@nileshlaxmi I will do my best to create a mock up, but it would be even better if you decide the things on your own and send a PR, then we can discuss the pros and cons of that design.

**Comment by nileshlaxmi** [comment]
Ok will do as u suggested.

**Comment by nileshlaxmi** [comment]
I wanted a rough pen paper sketch or mock up. You can later work on design.

**Comment by Contrevien** [comment]
@nileshlaxmi I will provide the mock up in few minutes

**Comment by nileshlaxmi** [comment]
Thanks

**Comment by Contrevien** [comment]
@nileshlaxmi @miteshree @dipakkr  The prototype is ready you can view it [here](https://www.figma.com/proto/VfVtvA8BzVXmDcCGCgj2kR2k/MockUp-Page-1-Mobile-v1.0?node-id=3%3A2&scaling=scale-down)

The hamburger menu will work, try it.

**Comment by HishamMubarak** [comment]
> @nileshlaxmi @miteshree @dipakkr The prototype is ready you can view it [here](https://www.figma.com/proto/VfVtvA8BzVXmDcCGCgj2kR2k/MockUp-Page-1-Mobile-v1.0?node-id=3%3A2&scaling=scale-down)
> 
> The hamburger menu will work, try it.

Prototype looks great.

**Comment by Contrevien** [comment]
@mitshree @HishamMubarak @nileshlaxmi Once again we need the nav bar to be converted to a hamburger menu, as in the mock up [here](https://www.figma.com/proto/VfVtvA8BzVXmDcCGCgj2kR2k/MockUp-Page-1-Mobile-v1.0?node-id=3%3A2&scaling=scale-down).

This time, try using media queries only though.

**Comment by Contrevien** [comment]
Solved for now, closing.
